# Generated by Django 5.1.4 on 2024-12-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0002_clinicalstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='clinical_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eln.clinicalstudy'),
        ),
        migrations.AddField(
            model_name='person',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eln.hospital'),
        ),
    ]
