# Generated by Django 5.1.4 on 2024-12-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0004_hospital_clinical_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eln.person')),
            ],
        ),
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eln.sample')),
            ],
        ),
    ]
