# Generated by Django 5.1.4 on 2024-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('opened', 'Opened'), ('closed', 'Closed')], default='received', max_length=8),
        ),
    ]
