# Generated by Django 5.1.4 on 2024-12-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0012_product_created_at_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kit', 'Kit'), ('primer', 'Primer')], default='kit', max_length=6),
        ),
    ]
