# Generated by Django 5.1.4 on 2024-12-26 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0014_vial_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vial',
            name='is_sediment',
            field=models.BooleanField(default=False),
        ),
    ]
