# Generated by Django 5.1.4 on 2024-12-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0019_experiment_comment_alter_person_clinical_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentCentrifugation',
            fields=[
                ('experiment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eln.experiment')),
                ('speed', models.IntegerField(default=2000, help_text='G')),
                ('duration', models.IntegerField(default=10, help_text='Minutes')),
                ('temperature', models.IntegerField(default=4, help_text='Degrees Celsius')),
            ],
            bases=('eln.experiment',),
        ),
    ]
