# Generated by Django 5.1.4 on 2024-12-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0020_experimentcentrifugation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRNAExtraction',
            fields=[
                ('experiment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eln.experiment')),
                ('kit', models.CharField(choices=[('urine_microrna_kit', 'Urine miRNA Kit'), ('mirneasy_advanced_mini_kit', 'miRNeasy Advanced Mini Kit'), ('mirneasy_serum_plasma_advanced_kit', 'miRNeasy Serum/Plasma Advanced Kit')], max_length=34)),
                ('input_volume', models.IntegerField(default=500, help_text='µL')),
                ('elution_volume', models.IntegerField(default=10, help_text='µL')),
            ],
            bases=('eln.experiment',),
        ),
    ]
