# Generated by Django 5.1.4 on 2024-12-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0021_experimentrnaextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentReverseTranscriptase',
            fields=[
                ('experiment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eln.experiment')),
                ('kit', models.CharField(choices=[('mircury_lna_rt_kit', 'miRCURY LNA RT Kit')], max_length=18)),
                ('rna_dilution', models.BooleanField(default=False)),
                ('dilution_rna_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('dilution_water_volume', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('input_volume', models.IntegerField(default=2, help_text='µL')),
            ],
            bases=('eln.experiment',),
        ),
    ]
