# Generated by Django 5.1.4 on 2024-12-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0024_kit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit',
            new_name='Primer',
        ),
    ]
