# Generated by Django 5.1.4 on 2024-12-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0026_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentQPCR',
            fields=[
                ('experiment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eln.experiment')),
                ('primer', models.ManyToManyField(to='eln.primer')),
            ],
            bases=('eln.experiment',),
        ),
    ]
