# Generated by Django 5.1.4 on 2024-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0028_remove_primer_type_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentreversetranscriptase',
            name='contain_spike_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experimentrnaextraction',
            name='contain_spike_in',
            field=models.BooleanField(default=True),
        ),
    ]
