# Generated by Django 5.1.4 on 2024-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0029_experimentreversetranscriptase_contain_spike_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='label',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vial',
            name='label',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
